CREATE TABLE TB_ESTADO(
	ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR(100) NOT NULL,
	SIGLA VARCHAR(2) NOT NULL
);

CREATE TABLE TB_CIDADE(
	ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR(100) NOT NULL,
	ID_ESTADO INT NOT NULL
);

CREATE TABLE TB_CLIENTE(
	ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR(100) NOT NULL,
	DATA_NASCIMENTO DATE NOT NULL,
	CPF VARCHAR(11) NOT NULL,
	EMAIL VARCHAR(100),
	ID_CIDADE INT NOT NULL,
	CEP VARCHAR(10) NOT NULL,
	BAIRRO VARCHAR(100) NOT NULL,
	LOGRADOURO VARCHAR(100) NOT NULL,
	NUMERO VARCHAR(5)
);

CREATE TABLE TB_TELEFONE(
	ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	DDD VARCHAR(3) NOT NULL,
	NUMERO VARCHAR(10) NOT NULL,
	TIPO VARCHAR(30) NOT NULL,
	ID_CLIENTE INT NOT NULL
);

CREATE TABLE TB_FORMA_PAGAMENTO(
	ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	DESCRICAO VARCHAR(100) NOT NULL
);

CREATE TABLE TB_ACORDO(
	ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	ID_CLIENTE INT NOT NULL,
	DATA_ACORDO TIMESTAMP NOT NULL,
	DESCRICAO TEXT NOT NULL,
	VALOR_TOTAL DECIMAL(6,2) NOT NULL,
    ID_FORMA_PAGAMENTO INT NOT NULL
);

CREATE TABLE TB_GUIA_PAGAMENTO(
	ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	ID_ACORDO INT NOT NULL,
	NUMERO_PARCELA INT NOT NULL,
	DATA_VENCIMENTO DATE NOT NULL,
	DATA_PAGAMENTO DATE,
	VALOR DECIMAL(6,2) NOT NULL,
	QUITADO BOOL NOT NULL
)