INSERT INTO TB_USUARIO(ID, NOME, LOGIN, SENHA, ATIVO) VALUES(1, 'Usuário teste', '12345', 'teste', TRUE);

INSERT INTO TB_CATEGORIA(ID, DESCRICAO, USUARIO_ID) VALUES(1, 'Alimentação', 1);
INSERT INTO TB_CATEGORIA(ID, DESCRICAO, USUARIO_ID) VALUES(2, 'Moradia', 1);
INSERT INTO TB_CATEGORIA(ID, DESCRICAO, USUARIO_ID) VALUES(3, 'Transporte', 1);
INSERT INTO TB_CATEGORIA(ID, DESCRICAO, USUARIO_ID) VALUES(4, 'Higiene', 1);
INSERT INTO TB_CATEGORIA(ID, DESCRICAO, USUARIO_ID) VALUES(5, 'Limpeza', 1);
INSERT INTO TB_CATEGORIA(ID, DESCRICAO, USUARIO_ID) VALUES(6, 'Salário', 1);

INSERT INTO TB_CONTA(CATEGORIA_ID, DESCRICAO, USUARIO_ID) VALUES(1, 'Refrigerante', 1);
INSERT INTO TB_CONTA(CATEGORIA_ID, DESCRICAO, USUARIO_ID) VALUES(1, 'Bolacha', 1);
INSERT INTO TB_CONTA(CATEGORIA_ID, DESCRICAO, USUARIO_ID) VALUES(1, 'Pães', 1);
INSERT INTO TB_CONTA(CATEGORIA_ID, DESCRICAO, USUARIO_ID) VALUES(2, 'Internet', 1);
INSERT INTO TB_CONTA(CATEGORIA_ID, DESCRICAO, USUARIO_ID) VALUES(2, 'Aluguel', 1);
INSERT INTO TB_CONTA(CATEGORIA_ID, DESCRICAO, USUARIO_ID) VALUES(2, 'Conta de Energia', 1);
INSERT INTO TB_CONTA(CATEGORIA_ID, DESCRICAO, USUARIO_ID) VALUES(6, 'Adiantamento', 1);
INSERT INTO TB_CONTA(CATEGORIA_ID, DESCRICAO, USUARIO_ID) VALUES(6, '2º parcela Salário', 1);
INSERT INTO TB_CONTA(CATEGORIA_ID, DESCRICAO, USUARIO_ID) VALUES(3, 'Uber', 1);
/*
INSERT INTO TB_LANCAMENTO(DATA, CATEGORIA_ID, CONTA_ID, VALOR, OPERACAO, OBSERVACAO, USUARIO_ID) VALUES('2019-05-21', 1, 3, 5.69, 1, 1);
INSERT INTO TB_LANCAMENTO(DATA, CATEGORIA_ID, CONTA_ID, VALOR, OPERACAO, OBSERVACAO, USUARIO_ID) VALUES('2019-05-20', 1, 2, 1.69, 1, 1);
INSERT INTO TB_LANCAMENTO(DATA, CATEGORIA_ID, CONTA_ID, VALOR, OPERACAO, OBSERVACAO, USUARIO_ID) VALUES('2018-05-01', 2, 5, 500.00, 1, 1);
INSERT INTO TB_LANCAMENTO(DATA, CATEGORIA_ID, CONTA_ID, VALOR, OPERACAO, OBSERVACAO, USUARIO_ID) VALUES('2018-01-11', 1, 3, 2.65, 1, 1);
INSERT INTO TB_LANCAMENTO(DATA, CATEGORIA_ID, CONTA_ID, VALOR, OPERACAO, OBSERVACAO, USUARIO_ID) VALUES('2019-01-20', 6, 8, 1200.00, 0, 1);
INSERT INTO TB_LANCAMENTO(DATA, CATEGORIA_ID, CONTA_ID, VALOR, OPERACAO, OBSERVACAO, USUARIO_ID) VALUES('2019-02-10', 3, 9, 11.60, 1, 1);
INSERT INTO TB_LANCAMENTO(DATA, CATEGORIA_ID, CONTA_ID, VALOR, OPERACAO, OBSERVACAO, USUARIO_ID) VALUES('2019-03-10', 3, 9, 9.69, 1, 1);
INSERT INTO TB_LANCAMENTO(DATA, CATEGORIA_ID, CONTA_ID, VALOR, OPERACAO, OBSERVACAO, USUARIO_ID) VALUES('2019-03-20', 6, 7, 968.00, 0, 1);
INSERT INTO TB_LANCAMENTO(DATA, CATEGORIA_ID, CONTA_ID, VALOR, OPERACAO, OBSERVACAO, USUARIO_ID) VALUES('2019-05-05', 1, 3, 1.69, 1, 1);
INSERT INTO TB_LANCAMENTO(DATA, CATEGORIA_ID, CONTA_ID, VALOR, OPERACAO, OBSERVACAO, USUARIO_ID) VALUES('2019-05-06', 1, 3, 3.79, 1, 1);
INSERT INTO TB_LANCAMENTO(DATA, CATEGORIA_ID, CONTA_ID, VALOR, OPERACAO, OBSERVACAO, USUARIO_ID) VALUES('2019-06-01', 2, 5, 500.00, 1, 1);
*/

INSERT INTO TB_LANCAMENTO(DATA, CATEGORIA_ID, CONTA_ID, VALOR, OPERACAO, OBSERVACAO, USUARIO_ID) VALUES('2019-05-21', 1, 3, 5.69, 'DEBITO', '', 1);
INSERT INTO TB_LANCAMENTO(DATA, CATEGORIA_ID, CONTA_ID, VALOR, OPERACAO, OBSERVACAO, USUARIO_ID) VALUES('2019-05-20', 1, 2, 1.69, 'DEBITO', '', 1);
INSERT INTO TB_LANCAMENTO(DATA, CATEGORIA_ID, CONTA_ID, VALOR, OPERACAO, OBSERVACAO, USUARIO_ID) VALUES('2018-05-01', 2, 5, 500.00, 'DEBITO', '', 1);
INSERT INTO TB_LANCAMENTO(DATA, CATEGORIA_ID, CONTA_ID, VALOR, OPERACAO, OBSERVACAO, USUARIO_ID) VALUES('2018-01-11', 1, 3, 2.65, 'DEBITO', '', 1);
INSERT INTO TB_LANCAMENTO(DATA, CATEGORIA_ID, CONTA_ID, VALOR, OPERACAO, OBSERVACAO, USUARIO_ID) VALUES('2019-01-20', 6, 8, 1200.00, 'CREDITO', '', 1);
INSERT INTO TB_LANCAMENTO(DATA, CATEGORIA_ID, CONTA_ID, VALOR, OPERACAO, OBSERVACAO, USUARIO_ID) VALUES('2019-02-10', 3, 9, 11.60, 'DEBITO', '', 1);
INSERT INTO TB_LANCAMENTO(DATA, CATEGORIA_ID, CONTA_ID, VALOR, OPERACAO, OBSERVACAO, USUARIO_ID) VALUES('2019-03-10', 3, 9, 9.69, 'DEBITO', '', 1);
INSERT INTO TB_LANCAMENTO(DATA, CATEGORIA_ID, CONTA_ID, VALOR, OPERACAO, OBSERVACAO, USUARIO_ID) VALUES('2019-03-20', 6, 7, 968.00, 'CREDITO', '', 1);
INSERT INTO TB_LANCAMENTO(DATA, CATEGORIA_ID, CONTA_ID, VALOR, OPERACAO, OBSERVACAO, USUARIO_ID) VALUES('2019-05-05', 1, 3, 1.69, 'DEBITO', '', 1);
INSERT INTO TB_LANCAMENTO(DATA, CATEGORIA_ID, CONTA_ID, VALOR, OPERACAO, OBSERVACAO, USUARIO_ID) VALUES('2019-05-06', 1, 3, 3.79, 'DEBITO', '', 1);
INSERT INTO TB_LANCAMENTO(DATA, CATEGORIA_ID, CONTA_ID, VALOR, OPERACAO, OBSERVACAO, USUARIO_ID) VALUES('2019-06-01', 2, 5, 500.00, 'DEBITO', '', 1);